name: Run tests and upload coverage

on: push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: ARTMashimbyi/-ConstitutionVault
          # Uncomment below line ONLY if the repo is private
          token: ${{ secrets.CODECOV_TOKEN }}
